version: "3"

services:
  fspd:
    image: ghcr.io/sephallen/fsp-server-docker:latest
    container_name: fspd
    restart: unless-stopped
    tty: true
    ports:
      - "7717:21/udp"
    volumes:
      - ./config/fspd.conf:/etc/fspd.conf
      - ./share:/var/ftp
